### ISSUE TITLE
Custom maven registry

### ISSUE THREAD

**Issue by chenrui333** [olafurpg/setup-scala#10]
We have in house maven registry, I wonder how I can use this action for it.

**Comment by olafurpg** [comment]
Thank you for reporting! This action only installs the JDK via jabba https://github.com/shyiko/jabba

The rest of the setup is left up to users to decide. Does that answer your question?

**Comment by chenrui333** [comment]
@olafurpg I am curious if there are any examples of doing it.

**Comment by olafurpg** [comment]
That’s a question for sbt or the build tool you are using. There’s not much this repo can help there.

**Comment by chenrui333** [comment]
OK, yeah, I wish there are more examples in the repo to help with the use. I will explore myself on this thing then. Thanks anyway!!
