### ISSUE TITLE
Graalvm image building broke possibly due to CI infrastructure?

### ISSUE THREAD

**Issue by drocsid** [olafurpg/setup-scala#21]
I've described the issue against the repository here: https://github.com/http4s/http4s.g8/issues/148

**Comment by drocsid** [comment]
It looks like the keys in jabba changed default graal jdk version to jdk 11. This breaks the key provided in the setup-scala documentation . https://github.com/shyiko/jabba/issues/683

**Comment by drocsid** [comment]
Why does setup-scala use a separate naming convention?

**Comment by olafurpg** [comment]
Thank you for reporting! Closing since the linked issue has been fixed https://github.com/http4s/http4s.g8/issues/148 Please reopen if this is still an issue
