### ISSUE TITLE
java9 runtime added?

### ISSUE THREAD

**Issue by er1c** [olafurpg/setup-scala#22]
```
[info] Compiling 53 Scala sources and 1 Java source to /home/runner/work/fm-common/fm-common/core/jvm/target/scala-2.11/test-classes ...
[error] /home/runner/work/fm-common/fm-common/core/jvm/src/test/scala/fm/common/TestPunycode.scala:346:20: object idn is not a member of package sun.net
[error]     import sun.net.idn.{Punycode => SunPunycode}
[error]    
```

Works fine locally, I think it's because I'm using official sbt instead of `sbt-extras`

It's related to making sure the java9+ runtime is available: (https://github.com/sbt/sbt-launcher-package/tree/master/java9-rt-export/src/main/java/io/github/retronym/java9rtexport)

**Comment by olafurpg** [comment]
Thank you for reporting! Can you elaborate on what is the issue? The Java version is configurable as documented here https://github.com/olafurpg/setup-scala#usage

The default Java version is the latest OpenJDK 8 HotSpot version via AdoptOpenJDK

**Comment by er1c** [comment]
This kind of works around the problem: https://github.com/er1c/fm-common/commit/179ce9dcf3579dec4c6d4ad22d5620d36efa62d0

But now I'm running  into an error about the jsdom library not being imported properly.

I think I just need to  use the official sbt-launcher script

**Comment by olafurpg** [comment]
I'm still not sure I understand the root issue. I use the current sbt launcher on Java 8 and 11 without issues

**Comment by olafurpg** [comment]
Closing since I'm not sure what is needed to resolve this issue.
