### ISSUE TITLE
Action name in the marketplace

### ISSUE THREAD

**Issue by laughedelic** [olafurpg/setup-scala#26]
The action is awesome! Thanks for creating it 💯 

It's strange that the name of this action in the marketplace is `setup-java`:
<img width="418" alt="Screenshot 2020-10-04 at 23 22 07" src="https://user-images.githubusercontent.com/766656/95027414-8b7db880-0698-11eb-8927-315a711e355c.png">

Apart from the obvious confusion, I think it makes the action less discoverable, because searching the market place for "scala" doesn't show it.

It's also strange that it says that the latest version is `v6`, while in the repo it's `v7`. 

I didn't find any mentions of `setup-java` in the repo, so I assume this is somehow configured in the marketplace.

**Comment by olafurpg** [comment]
Thank you for reporting! Good catch. I had noticed it before but then forgot about it. I delisted from the marketplace and published again and the name is now setup-scala :)

**Comment by olafurpg** [comment]
https://github.com/marketplace/actions/setup-scala

**Comment by laughedelic** [comment]
Cool!
