### ISSUE TITLE
v8 release is broken

### ISSUE THREAD

**Issue by ches** [olafurpg/setup-scala#27]
The archive for the `v8` tag does not contain the `lib/` directory with `main.js`, problem with the release automation?

**Comment by olafurpg** [comment]
Thank you for reporting! The v8 release was broken while I was fixing #26. I just force-pushed a new `v8` tag that fixes the issue. I validated it's working as expected now in https://github.com/olafurpg/sbt-ci-release/runs/1230912534?check_suite_focus=true We have CI in this repo but it doesn't test against the released versions.
