### ISSUE TITLE
Action doesn't work on ARM hosted runners

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/setup-scala#29]
The action only downloads the x86_64 variant of Jabba. It would be extremely useful if it could instead detect the ARM host and install the relevant binary instead. Alternatively, providing a configuration option would be sufficient, though less convenient.

**Comment by dimisjim** [comment]
Any news one this?

Would be really great to have this ability :tada:

**Comment by olafurpg** [comment]
Thank you for reporting! This should be fixed in https://github.com/olafurpg/setup-scala/releases/tag/v11 thanks to #39 by @vasilmkd
