### ISSUE TITLE
How to request graalvm with Java 11?

### ISSUE THREAD

**Issue by tovbinm** [olafurpg/setup-scala#4]
GraalVM 19.3.0 that was released recently comes with Java 11 support - https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by olafurpg** [comment]
Thank you for reporting! This project uses Jabba so that would require adding support for GraalVM 19.3 in Jabba, https://github.com/shyiko/jabba/issues/572

**Comment by olafurpg** [comment]
A workaround is to run the following commands before `sbt`

```
jabba install graal-custom@19.3=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-darwin-amd64-19.3.0.tar.gz
jabba use graal-custom@19.3
```

**Comment by olafurpg** [comment]
that works on macOS, you'll need a different URL for linux

**Comment by tovbinm** [comment]
Thanks!
