### ISSUE TITLE
Is it possible to install scaladoc

### ISSUE THREAD

**Issue by nh13** [olafurpg/setup-scala#47]
I'd like to install `scaladoc` to match the scala and jvm version, as I have a custom doclet I am using to generate docs.  I have tried coursier and homebrew, but that makes it difficult to reconcile with this action.  Is it possible to make `scaladoc` available on the path with this action?  If not, I'd be happy to contribute if you are open to and if you could point me in the right direction.

**Comment by olafurpg** [comment]
Thank you for reporting! This action does not support installing `scaladoc` but you can use https://github.com/coursier/setup-action instead, which supports installing custom apps including `scaladoc`.
