### ISSUE TITLE
Feature proposal - add cache example 

### ISSUE THREAD

**Issue by tovbinm** [olafurpg/setup-scala#6]
Add an example that uses Cache [`actions/cache@v1`](https://github.com/actions/cache)  that would cache:
1. JVM installation
2. SBT folder
3. Ivy folder

Example https://github.com/Kevin-Lee/maven2sbt/blob/master/.github/workflows/build.yml

**Comment by olafurpg** [comment]
Thank you for reporting! Caching was discussed in https://github.com/olafurpg/setup-scala/issues/5 and I'm still not convinced that caching delivers enough speedups to be worth it. What are your thoughts?

**Comment by tovbinm** [comment]
Thank you. I arrived to the same conclusion.
