### ISSUE TITLE
Color support in SBT

### ISSUE THREAD

**Issue by ruippeixotog** [olafurpg/setup-scala#9]
Hi! We're trying out GitHub Actions in PureConfig (https://github.com/pureconfig/pureconfig/pull/672) with your action. Everything works generally well, but ANSI colors aren't showing up in SBT tasks. I tried multiple combinations of `-Dsbt.color` and `-Dsbt.supershell` based on https://github.com/sbt/sbt/issues/4879 but I had no success. Do you have any idea of what might we be missing?

If we find out that a specific set of sbt options is needed, can we integrate them in this action? It seems like something that everyone wants on their CI jobs.

**Comment by olafurpg** [comment]
Thank you for reporting! I’m not sure what setup-scala can do to fix this issue. Maybe the sbt repo can provide more insights.
